# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.define "vm_apache"

    config.vm.box = "http://192.168.24.55/vagrant-boxes/focal64.box"
  
     config.vm.hostname = "vmteste"
     config.vm.network "forwarded_port", guest: 80, host: 8000, host_ip: "192.168.56.10"
     config.vm.network "private_network", ip: "192.168.56.10"
     config.vm.synced_folder "./htdocs", "/var/htdocs"
  
     config.vm.provider "virtualbox" do |vb|
      
       vb.memory = "1024"
       vb.cpus = "1"
     end
    
     config.vm.provision "shell", inline: <<-SHELL
       apt update
       sudo su
       apt install -y docker.io
       mkdir /var/htdocs
       chmod 755 /var/htdocs/ -R
       docker run -d -p 80:80 -v /var/htdocs/:/usr/local/apache2/htdocs/ httpd:2.4
     SHELL
  end